version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - .env
    working_dir: /app
    volumes:
      - "./backend:/app"

    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"

    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - "./frontend:/app"
    ports:
      - "5173:5173"
    tty: true
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
